config/routes.rb
Rails.application.routes.draw do

resources :wikis

  devise_for :users
  get "welcome/index"  
  
   root 'welcome#index'
   
   resources :charges, only: [:new, :create]
   
   get "/users/:id/role_toggle", to: "users#role_toggle", as: :role_toggle
  
#   post "/wikis/:id/add_collab", to: "wikis#add_collab", as: :add_collab
  
  
resources :users

end

app/models/amount.rb
class Amount < ActiveRecord::Base
    def self.default
        15_00
    end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  has_many :wikis
  
  has_many :collaborators
  has_many :wikis, through: :collaborators
  
  before_save { self.role ||= :standard }
  
  
  
  
  
  
  enum role: [:standard, :premium, :admin]

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  
  has_many :collaborators
  has_many :users, through: :collaborators
  
  
  validates :title, length: {minimum:5}, presence: true
  validates :body, length: {minimum: 20}, presence: true


    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController


 def create
   # Creates a Stripe Customer object, for associating
   # with the charge
   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )
 
   # Where the real magic happens
   charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: Amount.default,
     description: "BigMoney Membership - #{current_user.email}",
     currency: 'usd'
   )
   current_user.premium!
 
   flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
   redirect_to root_path # or wherever
 
   # Stripe will send back CardErrors, with friendly messages
   # when something goes wrong.
   # This `rescue block` catches and displays those errors.
   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
 end
 
    def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "BigMoney Membership - #{current_user.id}",
     amount: Amount.default
   }

    end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
    
    
def index 
   @collaborators =  Collaborator.all 
end

def create 
    wiki = Wiki.find(params[:id])
    user = User.find(params[:id])
    
    
    @collaborator = wiki.users << user
    
    if @collaborator.save
        flash[:notice] = "Collaborator added"
        redirect_to wiki
    else
        flash[:alert] = "Failed"
        redirect_to wiki
    end
end

def destroy 
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    
    def role_toggle
        current_user.wikis.each do |wiki| 
            wiki.private = false
            wiki.save
        end
        
        if current_user.premium?
            current_user.standard!
        end
        
        
        
        flash[:notice] = "Role changed to #{current_user.role}"
        redirect_to root_path
    end
      
      
      
    

        
        
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :signed_in, except: [:index, :show]
  before_action :user_auth, only: [:destroy]
  
  
   def index
     @wikis = policy_scope(Wiki)
   end

  def show
    @collaborators = Collaborator.all
    @wiki = Wiki.find(params[:id])
    @users = User.all
  end

  def new
    @wiki = Wiki.new
  end
  
  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user = current_user
    
    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash[:alert] = "There was an error in creating the Wiki. Please try again."
      render :new
    end
  end
  


  def edit
    @wiki = Wiki.find(params[:id])
  end
  
  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    
    #add collaborator
    unless params[:wiki][:user_id] == ""
      @collaborator = User.find(params[:wiki][:user_id])
      unless @wiki.users.include?(@collaborator)
        @wiki.users << @collaborator
      end
    end
    
    #remove collaborator
    unless params[:wiki][:user] == ""
      @wiki.users.delete(User.find(params[:wiki][:user]))
    end
    
    
    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash[:alert] = "There was an error in updating the Wiki. Please try again."
      render :edit
    end
    
  end
  
  # Use outside of create method
  # def add_collab
  #   @collaborator = User.find(params[:wiki][:user_id])
  #   unless @wiki.users.include?(@collaborator)
  #     @wiki.users << @collaborator
  #   end
  # end
  
  # def remove_collab
  #   @wiki.users.delete(User.find(params[:wiki][:user]))
  # end
  
  
  def destroy
    @wiki = Wiki.find(params[:id])
    
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
       redirect_to wikis_path
     else
       flash.now[:alert] = "There was an error deleting the wiki."
       render :show
    end
  end
  
  private
  
  def signed_in
    unless current_user
    flash[:alert] = "You must be logged in to do this!"
    redirect_to new_user_session_path
    end
  end
  
  def user_auth
    wiki = Wiki.find(params[:id])
    unless current_user == wiki.user || current_user.admin? || current_user.premium?
    flash[:alert] = "You must be the owner to do this!"
    redirect_to wikis_path
    end
  end
  
  

  
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    
   def markdown(text)
       options = {
           filter_html: true,
           hard_wrap: true,
           space_after_headers: true,
           fenced_code_blocks: true
           
       }
       
       extensions = {
           autolink: true,
           disable_indented_code_blocks: true
           
       }
       
       renderer = Redcarpet::Render::HTML.new(options)
       markdown = Redcarpet::Markdown.new(renderer, extensions)
       
       markdown.render(text).html_safe
   end
   
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
    def collaborator_for(logged_in_user)
      @wiki.users.each do |user|
        if user.id == logged_in_user.id
          false
        end
      end
    end
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
   <h4>Click the button!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

app/views/collaborators/_collaborator.html.erb
collection_select(:wiki, :user_id, User.all, :id, prompt: true)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
 <% if user_signed_in? %>
 <div class="pull-right">
   Signed in as: <strong><%= current_user.email %></strong> |
   <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> |
 <% else %>
 # #2
   <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
   <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
 <% end %>
 <% if user_signed_in? && current_user.premium? %>
   <%= link_to "Downgrade", role_toggle_path(current_user.id), :data => {:confirm => 'Are you sure, all private wikis will become public?'} %>
 <% end %>
 </div>


 
 <h3><%= link_to "Wikis", wikis_path, class: 'navbar-link pull-left' %></h3>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
</body>
</html>

app/views/users/index.html.erb
<h1> Users</h1>

<% @users.each do |user| %>
    <%= link_to user.email,  user%>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1><%=@user.email %></h1>

app/views/welcome/index.html.erb
<br>
 <div class="jumbotron">
   <h1>Blocipedia</h1>
   <p>Blocipedia the wiki of Bloc</p>
 </div>

 

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
   <div>
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
       </div>
       <% if current_user.premium? || current_user.admin? %>
         <div class="form-group">
            <%= f.label :private, class: 'checkbox' %>
            <%= f.check_box :private %> Private wiki
         </div>
       <% end %>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
      <div>
        <h3>Add collaborator</h3>
            <%= f.collection_select :user_id, User.all, :id, :email,  include_blank: true %>
            <%= f.submit "Add", class: 'btn btn-sucess' %>
      </div>
      <div>
         <h3>Remove collaborator</h3>
            <%= f.collection_select :user, @wiki.users, :id, :email,  include_blank: true %>
            <%= f.submit "Remove", class: 'btn btn-danger'%>
      </div>
     <% end %>

   </div>

app/views/wikis/index.html.erb
<h1>Wikis</h1>
<% @wikis.each do |wiki| %>
<div class="media">
    <div class="media-body">
        <h4 class="media-heading">
            <p>
                <%= link_to wiki.title, wiki %>
            </p>
        </h4>
    </div>
</div>
<% end %>
<div>
    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
</div>

app/views/wikis/new.html.erb
 <h2> New Wiki</h2>
 <div class= "row">
  <%= form_for @wiki do |f| %>
   <div class="col-md-12">
    <div class="form-group">
     <%= f.label :title %>
     <%= f.text_field :title %>
    </div>
    <div class="form-group">
     <%= f.label :body %>
     <%= f.text_area :body %>
     </div>
     <% if current_user.premium? || current_user.admin? %>
     <div class="form-group">
     <%= f.label :private, class: 'checkbox' %>
     <%= f.check_box :private %> Private wiki
    </div>
    <% end %>
    <div class="form-group">
     <%= f.submit "Save" %>
     </div>
   </div>
   <% end %>
 </div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>
<p><%= markdown(@wiki.body) %></p>

<% if current_user.premium? || current_user.admin? || current_user.id == @wiki.user_id || @wiki.users.include?(current_user) %>
<%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
<% end %>
<%= link_to "Delete Post", @post, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>

<h3>Collaborators</h3>
<% @wiki.users.each do |collaborator| %>
<ul>
    <li><%= User.find(collaborator.id).email %></li>
</ul>





<% end %>
  